/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardWebsiteRouteImport } from './routes/dashboard_.website'
import { Route as DashboardProfileRouteImport } from './routes/dashboard_.profile'
import { Route as DashboardLibraryRouteImport } from './routes/dashboard_.library'
import { Route as DashboardAdsRouteImport } from './routes/dashboard_.ads'
import { Route as DashboardBibleNewRouteImport } from './routes/dashboard_.bible.new'
import { Route as DashboardBibleIdRouteImport } from './routes/dashboard_.bible.$id'
import { Route as DashboardAgentIdRouteImport } from './routes/dashboard_.agent.$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWebsiteRoute = DashboardWebsiteRouteImport.update({
  id: '/dashboard_/website',
  path: '/dashboard/website',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard_/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLibraryRoute = DashboardLibraryRouteImport.update({
  id: '/dashboard_/library',
  path: '/dashboard/library',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdsRoute = DashboardAdsRouteImport.update({
  id: '/dashboard_/ads',
  path: '/dashboard/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBibleNewRoute = DashboardBibleNewRouteImport.update({
  id: '/dashboard_/bible/new',
  path: '/dashboard/bible/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBibleIdRoute = DashboardBibleIdRouteImport.update({
  id: '/dashboard_/bible/$id',
  path: '/dashboard/bible/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAgentIdRoute = DashboardAgentIdRouteImport.update({
  id: '/dashboard_/agent/$id',
  path: '/dashboard/agent/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/agent/$id': typeof DashboardAgentIdRoute
  '/dashboard/bible/$id': typeof DashboardBibleIdRoute
  '/dashboard/bible/new': typeof DashboardBibleNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/library': typeof DashboardLibraryRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/website': typeof DashboardWebsiteRoute
  '/dashboard/agent/$id': typeof DashboardAgentIdRoute
  '/dashboard/bible/$id': typeof DashboardBibleIdRoute
  '/dashboard/bible/new': typeof DashboardBibleNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/dashboard_/ads': typeof DashboardAdsRoute
  '/dashboard_/library': typeof DashboardLibraryRoute
  '/dashboard_/profile': typeof DashboardProfileRoute
  '/dashboard_/website': typeof DashboardWebsiteRoute
  '/dashboard_/agent/$id': typeof DashboardAgentIdRoute
  '/dashboard_/bible/$id': typeof DashboardBibleIdRoute
  '/dashboard_/bible/new': typeof DashboardBibleNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/ads'
    | '/dashboard/library'
    | '/dashboard/profile'
    | '/dashboard/website'
    | '/dashboard/agent/$id'
    | '/dashboard/bible/$id'
    | '/dashboard/bible/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard/ads'
    | '/dashboard/library'
    | '/dashboard/profile'
    | '/dashboard/website'
    | '/dashboard/agent/$id'
    | '/dashboard/bible/$id'
    | '/dashboard/bible/new'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/dashboard_/ads'
    | '/dashboard_/library'
    | '/dashboard_/profile'
    | '/dashboard_/website'
    | '/dashboard_/agent/$id'
    | '/dashboard_/bible/$id'
    | '/dashboard_/bible/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DashboardAdsRoute: typeof DashboardAdsRoute
  DashboardLibraryRoute: typeof DashboardLibraryRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardWebsiteRoute: typeof DashboardWebsiteRoute
  DashboardAgentIdRoute: typeof DashboardAgentIdRoute
  DashboardBibleIdRoute: typeof DashboardBibleIdRoute
  DashboardBibleNewRoute: typeof DashboardBibleNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/website': {
      id: '/dashboard_/website'
      path: '/dashboard/website'
      fullPath: '/dashboard/website'
      preLoaderRoute: typeof DashboardWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/profile': {
      id: '/dashboard_/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/library': {
      id: '/dashboard_/library'
      path: '/dashboard/library'
      fullPath: '/dashboard/library'
      preLoaderRoute: typeof DashboardLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/ads': {
      id: '/dashboard_/ads'
      path: '/dashboard/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof DashboardAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/bible/new': {
      id: '/dashboard_/bible/new'
      path: '/dashboard/bible/new'
      fullPath: '/dashboard/bible/new'
      preLoaderRoute: typeof DashboardBibleNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/bible/$id': {
      id: '/dashboard_/bible/$id'
      path: '/dashboard/bible/$id'
      fullPath: '/dashboard/bible/$id'
      preLoaderRoute: typeof DashboardBibleIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/agent/$id': {
      id: '/dashboard_/agent/$id'
      path: '/dashboard/agent/$id'
      fullPath: '/dashboard/agent/$id'
      preLoaderRoute: typeof DashboardAgentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DashboardAdsRoute: DashboardAdsRoute,
  DashboardLibraryRoute: DashboardLibraryRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardWebsiteRoute: DashboardWebsiteRoute,
  DashboardAgentIdRoute: DashboardAgentIdRoute,
  DashboardBibleIdRoute: DashboardBibleIdRoute,
  DashboardBibleNewRoute: DashboardBibleNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
